# Multivariate Linear Regression

### Importing the libraries and the dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

companies = pd.read_csv('1000_Companies.csv')

### Adjusting the dataset

In [3]:
companies.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
companies.State.unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [5]:
# The "State" column is in categorical data form, wich makes harder to do an analysis. Thus, we gonna' make it numerical using a pandas method.
companies['State'] = companies['State'].replace(['New York','California','Florida'],[0,1,2])
companies

     R&D Spend  Administration  Marketing Spend  State        Profit
0    165349.20      136897.800      471784.1000      0  192261.83000
1    162597.70      151377.590      443898.5300      1  191792.06000
2    153441.51      101145.550      407934.5400      2  191050.39000
3    144372.41      118671.850      383199.6200      0  182901.99000
4    142107.34       91391.770      366168.4200      2  166187.94000
..         ...             ...              ...    ...           ...
995   54135.00      118451.999      173232.6695      1   95279.96251
996  134970.00      130390.080      329204.0228      1  164336.60550
997  100275.47      241926.310      227142.8200      1  413956.48000
998  128456.23      321652.140      281692.3200      1  333962.19000
999  161181.72      270939.860      295442.1700      0  476485.43000

[1000 rows x 5 columns]

### Now lets define the labels and variables and split the dataset into training and testing

In [7]:
X = companies.iloc[:,:-1]
y = companies['Profit']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=0)
X_train

     R&D Spend  Administration  Marketing Spend  State
687    38385.0     116125.9672     142843.00150      1
500   125610.0     129007.7526     311143.87720      2
332   101322.0     125420.7901     264280.11490      1
979    12914.0     112364.2939      93696.63744      1
817   109909.0     126688.9574     280848.75480      0
..         ...             ...              ...    ...
835   110391.0     126760.1413     281778.77510      1
192    53078.0     118295.8964     171193.18510      1
629    22876.0     113835.5275     112918.34360      1
559    66766.0     120317.4026     197604.21850      1
684   112108.0     127013.7157     285091.73130      1

[800 rows x 4 columns]

### Now lets choose the model and fit it with the training set

In [8]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

#### Lets predict using the test data

In [11]:
y_pred = lr.predict(X_test)

# We've just calculated the predicted values usiong the model made from the training data. Now we need to know if its good enough, so we will compare it to te real data.

from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

# 91,1% its a pretty good fit!

0.9117977860104945